In [14]:
# 3.1.1 データフローグラフ
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(1)
c = a + b

print(c.numpy())

2


In [24]:
import tensorflow as tf

a = tf.Variable(1)
b = tf.constant(1)
c = a + b
print(c.numpy())
a.assign(a + b)
c = a + b
print(c.numpy())

2
3


In [26]:
# 3.2.1 データフローグラフ
import tensorflow as tf

b = tf.constant(2)
b = tf.constant(3)
c = a + b
d = a * b
print(c.numpy())
print(d.numpy())

5
6


In [27]:
#3.3 多次元配列とテンソル
import tensorflow as tf

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = a + b

print(c.numpy())

[5 7 9]


In [43]:
import tensorflow as tf

a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[1], [2]])
c = tf.matmul(a, b)

print(a.shape)
print(b.shape)
print(c.shape)
print(a.numpy())
print(b.numpy())
print(c.numpy())

(2, 2)
(2, 1)
(2, 1)
[[1 2]
 [3 4]]
[[1]
 [2]]
[[ 5]
 [11]]
